using Average;
using CalculateRectangle;
using CalculateTables;
using Comments;
using Dimension;
using Distance;
using Division;
using EquivalentProgram;
using KelvinFahrenheit;
using MyNamespace;
using Printing;
using Priority;
using ProductThreeFactors;
using Reverse;
using Square;
using Storeinput;
using Task;
using GeometrySquare;
using GeometryRectangle;
using BasicCalculatorProgram;
using Switch;
using PositiveNegative;
using LargestNumber;
using WhileProgram;
using ProgramDoWhile;
using RangeProgram;
using SumInfiniteProgram;
using NumberRepeated;
using MultiplicationTable;
using MathematicalStatistics;
using InfiniteMultiple;
using ProgramAccess;
using RandomNumber;
using AssignmentProgram;
using Library2;
using ProgramOutput;
using Product;
using AbsoluteProgram;
using PrimeProgram;
using DigitProgram;
using DescendingProgram;
using VowelsSwitch;
using FunctionEquation;
using TriangleProgram;
using TriangleNE;
using RightAngleTriangle;
using AlphabetProgram;
using ConditionalProgram;
using NumberException;
using BooleanProgram;
using PatternProgram;
using InvertedPattern;
using PyramidProgram;
using RightTiangleProgram;
using SquarePattern;
using HollowSquarePattern;
using LeftTrianglePattern;
using CharacterPyramidPattern;
using ReverseProgram;
using CondtionalOperatorProgram;
using GiveChangeProgram;
using StructProgram;





//SayingHello.Solution1();
//PrintLine.Solution();
//ReadInput.Solution();
//UserInput.Solution();
//MultiLine.Solution();
//CalculateSurfaceVolume.Solution();
//BasicCalculator.Solution();
//ReverseChars.Solution();
//CalculateCelsiusToKF.Solution();
//Rectangle.Solution();
//CalculateSpeed.Solution();
//Multiplication.Solution();
//RandomNumber.Solution();
//SquareTheValue.Solution();
//MultipleThreeValues.Solution();
//CalculateDivision.Solution();
//OrderOfPriority.Solution();
//AverageProgram.Solution();
//EquivalentOperations.Solution();
//PaintTheSquare.Solution();
//RectangleDraw.Solution();
//BasicOperation.Solution();
//SwitchCalculator.Solution();
//CalculatePositiveNegative.Solution();
//GreatestNumber.Solution();
//InstructionWhile.Solution();
//InstructionDoWhile.Solution();
//CalculateRange.Solution();
//Infinite.Solution();
//CalculateRepeated.Solution();
//InfiniteMultiplicationTable.Solution();
//Statistics.Solution();
//MultiplesNumber.Solution();
//AccessControl.Solution();
//GenerateRandomNumber.Solution();
//Assignment.Solution();
//ProductNumber.Solution();
//Absolute.Solution();
//CalculatePrime.Solution();
//Helper.Demo1();
//DigitNumber.Solution();
//OddNumber.Solution();
//Vowel.Solution();
//MathematicalProgram.Solution();
//Triangle.Solution();
//NorthEastTriangle.Solution();
//RightTriangle.Solution();
//CharAlphabet.Solution();
//Conditional.Solution();
//ExceptionProgram.Solution();
//PrintingMethods.Solution2();
//CalculateBoolean.Solution();
//Patterns.Solution();
//InvertedRightTriangle.Solution();
//Pyramid.Solution();
//RightAlignedTriangle.Solution();
//SquareProgram.Solution();
//SquareMiddleGap.Solution();
//HollowSquare.Solution();
//LeftTriangle.Solution();
//CharacterPyramid.Solution();
//ReverseOrder.Solution();
//EvenNumbers.Solution();
//ConditionalOperator.Solution();
//GiveChange.Solution();
//Struct.Solution();

